#!/bin/bash

mkdir -p ~/.zsh
cp -r ./zsh/* ~/.zsh
cp zshrc ~/.zshrc

`asdf plugin add direnv`
`asdf direnv setup --shell bash --version system`

echo "Welcome to `hostname` `whoami`"
echo "Run `bash ~/.dotfiles/now-zsh` to finish up"


git config --global merge.tool opendiff
