#!/bin/bash

mkdir -p ~/.zsh
cp -r ./zsh/* ~/.zsh
cp zshrc ~/.zshrc

`/opt/homebrew/bin/asdf plugin add direnv`
`/opt/homebrew/bin/asdf direnv setup --shell bash --version system`

echo "Welcome to `hostname` `whoami`"
echo "Run `bash ~/.dotfiles/script/now-zsh` to finish up"

git config --global merge.tool opendiff
